In [1]:
import os
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('D:\Bachelors\Semester2\VDSS\project_folder\VDSS_Visualisierungsprojekt\clean_data\\2017.csv')
df

,Country,Happiness.Rank,Happiness.Score,Whisker.high,Whisker.low,Economy..GDP.per.Capita.,Family,Health..Life.Expectancy.,Freedom,Generosity,Trust..Government.Corruption.,Dystopia.Residual
0,Norway,1,7.537,7.594445,7.479556,1.616463,1.533524,0.796667,0.635423,0.362012,0.315964,2.277027
1,Denmark,2,7.522,7.581728,7.462272,1.482383,1.551122,0.792566,0.626007,0.355280,0.400770,2.313707
2,Iceland,3,7.504,7.622030,7.385970,1.480633,1.610574,0.833552,0.627163,0.475540,0.153527,2.322715
3,Switzerland,4,7.494,7.561772,7.426227,1.564980,1.516912,0.858131,0.620071,0.290549,0.367007,2.276716
4,Finland,5,7.469,7.527542,7.410458,1.443572,1.540247,0.809158,0.617951,0.245483,0.382612,2.430182
...,...,...,...,...,...,...,...,...,...,...,...,...
150,Rwanda,151,3.471,3.543030,3.398970,0.368746,0.945707,0.326425,0.581844,0.252756,0.455220,0.540061
151,Syria,152,3.462,3.663669,3.260331,0.777153,0.396103,0.500533,0.081539,0.493664,0.151347,1.061574
152,Tanzania,153,3.349,3.461430,3.236570,0.511136,1.041990,0.364509,0.390018,0.354256,0.066035,0.621130
153,Burundi,154,2.905,3.074690,2.735310,0.091623,0.629794,0.151611,0.059901,0.204435,0.084148,1.683024
154,Central African Republic,155,2.693,2.864884,2.521116,0.000000,0.000000,0.018773,0.270842,0.280876,0.056565,2.066005

In [3]:
df.rename(columns = {'Happiness.Rank':'Happiness Rank','Happiness.Score':'Happiness Score','Whisker.high':'Upper Confidence Interval','Whisker.low':'Lower Confidence Interval','Economy..GDP.per.Capita.':'Economy (GDP per Capita)','Health..Life.Expectancy.': 'Health (Life Expectancy)','Trust..Government.Corruption.':'Trust (Government Corruption)','Dystopia.Residual':'Dystopia Residual','Freedom':'Freedom to make life choices','Family':'Social support'}, inplace = True)
df

,Country,Happiness Rank,Happiness Score,Upper Confidence Interval,Lower Confidence Interval,Economy (GDP per Capita),Social support,Health (Life Expectancy),Freedom to make life choices,Generosity,Trust (Government Corruption),Dystopia Residual
0,Norway,1,7.537,7.594445,7.479556,1.616463,1.533524,0.796667,0.635423,0.362012,0.315964,2.277027
1,Denmark,2,7.522,7.581728,7.462272,1.482383,1.551122,0.792566,0.626007,0.355280,0.400770,2.313707
2,Iceland,3,7.504,7.622030,7.385970,1.480633,1.610574,0.833552,0.627163,0.475540,0.153527,2.322715
3,Switzerland,4,7.494,7.561772,7.426227,1.564980,1.516912,0.858131,0.620071,0.290549,0.367007,2.276716
4,Finland,5,7.469,7.527542,7.410458,1.443572,1.540247,0.809158,0.617951,0.245483,0.382612,2.430182
...,...,...,...,...,...,...,...,...,...,...,...,...
150,Rwanda,151,3.471,3.543030,3.398970,0.368746,0.945707,0.326425,0.581844,0.252756,0.455220,0.540061
151,Syria,152,3.462,3.663669,3.260331,0.777153,0.396103,0.500533,0.081539,0.493664,0.151347,1.061574
152,Tanzania,153,3.349,3.461430,3.236570,0.511136,1.041990,0.364509,0.390018,0.354256,0.066035,0.621130
153,Burundi,154,2.905,3.074690,2.735310,0.091623,0.629794,0.151611,0.059901,0.204435,0.084148,1.683024
154,Central African Republic,155,2.693,2.864884,2.521116,0.000000,0.000000,0.018773,0.270842,0.280876,0.056565,2.066005

In [4]:
def swap_columns(df, col1, col2):
    col_list = list(df.columns)
    x, y = col_list.index(col1), col_list.index(col2)
    col_list[y], col_list[x] = col_list[x], col_list[y]
    df = df[col_list]
    return df

#swap points and rebounds columns
df = swap_columns(df, 'Lower Confidence Interval','Upper Confidence Interval')
df = swap_columns(df, 'Trust (Government Corruption)','Generosity')
df

,Country,Happiness Rank,Happiness Score,Lower Confidence Interval,Upper Confidence Interval,Economy (GDP per Capita),Social support,Health (Life Expectancy),Freedom to make life choices,Trust (Government Corruption),Generosity,Dystopia Residual
0,Norway,1,7.537,7.479556,7.594445,1.616463,1.533524,0.796667,0.635423,0.315964,0.362012,2.277027
1,Denmark,2,7.522,7.462272,7.581728,1.482383,1.551122,0.792566,0.626007,0.400770,0.355280,2.313707
2,Iceland,3,7.504,7.385970,7.622030,1.480633,1.610574,0.833552,0.627163,0.153527,0.475540,2.322715
3,Switzerland,4,7.494,7.426227,7.561772,1.564980,1.516912,0.858131,0.620071,0.367007,0.290549,2.276716
4,Finland,5,7.469,7.410458,7.527542,1.443572,1.540247,0.809158,0.617951,0.382612,0.245483,2.430182
...,...,...,...,...,...,...,...,...,...,...,...,...
150,Rwanda,151,3.471,3.398970,3.543030,0.368746,0.945707,0.326425,0.581844,0.455220,0.252756,0.540061
151,Syria,152,3.462,3.260331,3.663669,0.777153,0.396103,0.500533,0.081539,0.151347,0.493664,1.061574
152,Tanzania,153,3.349,3.236570,3.461430,0.511136,1.041990,0.364509,0.390018,0.066035,0.354256,0.621130
153,Burundi,154,2.905,2.735310,3.074690,0.091623,0.629794,0.151611,0.059901,0.084148,0.204435,1.683024
154,Central African Republic,155,2.693,2.521116,2.864884,0.000000,0.000000,0.018773,0.270842,0.056565,0.280876,2.066005

In [5]:
nan_df = df[df.isna().any(axis=1)]
display(nan_df.head())

df = df.dropna(how='any')
df

Empty DataFrame
Columns: [Country, Happiness Rank, Happiness Score, Lower Confidence Interval, Upper Confidence Interval, Economy (GDP per Capita), Social support, Health (Life Expectancy), Freedom to make life choices, Trust (Government Corruption), Generosity, Dystopia Residual]
Index: []

,Country,Happiness Rank,Happiness Score,Lower Confidence Interval,Upper Confidence Interval,Economy (GDP per Capita),Social support,Health (Life Expectancy),Freedom to make life choices,Trust (Government Corruption),Generosity,Dystopia Residual
0,Norway,1,7.537,7.479556,7.594445,1.616463,1.533524,0.796667,0.635423,0.315964,0.362012,2.277027
1,Denmark,2,7.522,7.462272,7.581728,1.482383,1.551122,0.792566,0.626007,0.400770,0.355280,2.313707
2,Iceland,3,7.504,7.385970,7.622030,1.480633,1.610574,0.833552,0.627163,0.153527,0.475540,2.322715
3,Switzerland,4,7.494,7.426227,7.561772,1.564980,1.516912,0.858131,0.620071,0.367007,0.290549,2.276716
4,Finland,5,7.469,7.410458,7.527542,1.443572,1.540247,0.809158,0.617951,0.382612,0.245483,2.430182
...,...,...,...,...,...,...,...,...,...,...,...,...
150,Rwanda,151,3.471,3.398970,3.543030,0.368746,0.945707,0.326425,0.581844,0.455220,0.252756,0.540061
151,Syria,152,3.462,3.260331,3.663669,0.777153,0.396103,0.500533,0.081539,0.151347,0.493664,1.061574
152,Tanzania,153,3.349,3.236570,3.461430,0.511136,1.041990,0.364509,0.390018,0.066035,0.354256,0.621130
153,Burundi,154,2.905,2.735310,3.074690,0.091623,0.629794,0.151611,0.059901,0.084148,0.204435,1.683024
154,Central African Republic,155,2.693,2.521116,2.864884,0.000000,0.000000,0.018773,0.270842,0.056565,0.280876,2.066005

In [6]:
df=df.drop(columns=['Lower Confidence Interval','Upper Confidence Interval','Generosity','Dystopia Residual'])
df

,Country,Happiness Rank,Happiness Score,Economy (GDP per Capita),Social support,Health (Life Expectancy),Freedom to make life choices,Trust (Government Corruption)
0,Norway,1,7.537,1.616463,1.533524,0.796667,0.635423,0.315964
1,Denmark,2,7.522,1.482383,1.551122,0.792566,0.626007,0.400770
2,Iceland,3,7.504,1.480633,1.610574,0.833552,0.627163,0.153527
3,Switzerland,4,7.494,1.564980,1.516912,0.858131,0.620071,0.367007
4,Finland,5,7.469,1.443572,1.540247,0.809158,0.617951,0.382612
...,...,...,...,...,...,...,...,...
150,Rwanda,151,3.471,0.368746,0.945707,0.326425,0.581844,0.455220
151,Syria,152,3.462,0.777153,0.396103,0.500533,0.081539,0.151347
152,Tanzania,153,3.349,0.511136,1.041990,0.364509,0.390018,0.066035
153,Burundi,154,2.905,0.091623,0.629794,0.151611,0.059901,0.084148
154,Central African Republic,155,2.693,0.000000,0.000000,0.018773,0.270842,0.056565